version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - ./dev/mysql:/var/lib/mysql
    restart: unless-stopped
    
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./dev/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev
      MONGO_INITDB_DATABASE: dev
      DB_NAME: dev
      DB_USER: dev
      DB_PASSWORD: dev
    volumes:
      - ./dev/mongodb:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    restart: unless-stopped

  mail:
    image: mailserver/docker-mailserver:latest
    container_name: mail
    hostname: mail
    domainname: example.com
    environment:
      ENABLE_SPAMASSASSIN: 0
      ENABLE_CLAMAV: 0
      ENABLE_FAIL2BAN: 0
      ENABLE_POSTGREY: 0
      ENABLE_SASLAUTHD: 1
      PERMIT_DOCKER: network
      ONE_DIR: 1
      SSL_TYPE: manual
      TLS_LEVEL: modern
      SASL_PASSWD: no-reply@example.com:dev
    ports:
      - "127.0.0.1:9925:25"
      - "127.0.0.1:9587:587"
      - "127.0.0.1:9993:993"
    volumes:
      - ./dev/mail/maildata:/var/mail
      - ./dev/mail/mailstate:/var/mail-state
      - ./dev/mail/maillogs:/var/log/mail
      - ./dev/mail/config:/tmp/docker-mailserver
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9
    ports:
      - "127.0.0.1:9953:53/udp"
      - "127.0.0.1:9953:53/tcp"
    volumes:
      - ./dev/bind9/named.conf:/etc/bind/named.conf:ro
      - ./dev/bind9/named.conf.local:/etc/bind/named.conf.local:ro
      - ./dev/bind9/db.example.com:/etc/bind/db.example.com:ro
    environment:
      - TZ=UTC
    cap_add:
      - NET_BIND_SERVICE
    restart: unless-stopped
