version: '3.8'

services:

  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    volumes:
      - ./dev/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev
      MONGO_INITDB_DATABASE: dev
      DB_NAME: dev
      DB_USER: dev
      DB_PASSWORD: dev
    volumes:
      - ./dev/mongodb:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    restart: unless-stopped

  smtp:
    image: boky/postfix:latest
    container_name: postfix
    environment:
      HOSTNAME: mail.example.com
      ALLOW_EMPTY_SENDER_DOMAINS: 'true'
    volumes:
      - ./dev/postfix:/etc/opendkim/keys
    ports:
      - "127.0.0.1:2525:25"
    restart: unless-stopped

  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9
    ports:
      - "127.0.0.1:5353:53/udp"
      - "127.0.0.1:5353:53/tcp"
    volumes:
      - ./dev/bind9/named.conf:/etc/bind/named.conf:ro
      - ./dev/bind9/named.conf.local:/etc/bind/named.conf.local:ro
      - ./dev/bind9/db.example.com:/etc/bind/db.example.com:ro
    environment:
      - TZ=UTC
    cap_add:
      - NET_BIND_SERVICE
    restart: unless-stopped
